name: flutter_login_page
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.1
  flutter_signin_button: ^1.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  video_player: ^0.10.6
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  firebase_core: any
  firebase_database: ^3.1.1
  flutter_screenutil: ^0.5.2
  intl: ^0.16.1
  date_format: ^1.0.8
  outline_material_icons: ^0.1.0
  sqflite: ^1.2.0
  shared_preferences: ^0.5.3+1
  share: ^0.6.1+1
  path_provider: ^1.6.0
  validators: ^2.0.0+1
  flutter_dialogflow: ^0.1.3
  camera: ^0.5.7+3
  path: ^1.6.4
  google_maps_flutter: ^0.5.22+1
  location: ^2.3.5
  user_location: ^0.1.1
  flutter_polyline_points: ^0.1.0
  geolocator: ^5.2.1
  url_launcher: ^5.4.1
  timeago: ^2.0.26
  carousel_pro: ^1.0.0
  carousel_slider: ^1.4.1
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.4+2
  nepali_date_picker: ^3.2.0+1
  nepali_utils: ^2.2.0+2
  firebase_messaging: ^6.0.9
  like_button: ^0.2.0
  flutter_launcher_icons: ^0.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/a.jpg
    - assets/b.jpg
    - assets/c.jpg
    - assets/c.jpg
    - assets/d.jpg
    - assets/j.jpg
    - assets/d.png
    - assets/k.jpg
    - assets/f.jpg
    - assets/g.jpg
    - assets/h.jpg
    - assets/i.jpg
    - assets/write.png
    - assets/image.png
    - assets/image_02.png
    - assets/logo.png
    - assets/google.png
    - images/original.png
    - images/APNT1I.jpg
    - images/mountain.png
    - images/jatra.png
    - images/culture.PNG
    - images/banglamukhi.jpg
    - images/basantapur.jpg
    - images/boudhanath.jpg
    - images/Ghodejatra.jpg
    - images/Gyalpo_lhosar.jpg
    - images/Holi.jpg
    - images/nepal.jpg
    - images/nepal1.jpg
    - images/pas.png
    - images/patan.jpeg
    - images/Ramnawami.jpeg
    - images/Shivaratri.jpg
    - assets/plans.db
    - assets/inviteImage.png
    - assets/images/
    - images/gyal1.jpg
    - images/gyal2.jpg
    - images/gyal3.jpg
    - images/Holi.jpg
    - images/holi1.jpg
    - images/holi2.jpg
    - images/Ramnawami.jpeg
    - images/ram1.jpg
    - images/ram2.jpg
    - images/Ghodejatra.jpg
    - images/gh1.jpg
    - images/gh2.jpg
    - images/swyam.jpg
    - images/swyam1.jpg
    - images/swyam2.jpg
    - images/swyam3.jpg
    - images/swyam4.jpg
    - images/basantapur.jpg
    - images/bas1.jpg
    - images/bas2.jpeg
    - images/bas3.jpg
    - images/bas4.jpg
    - images/boudhanath.jpg
    - images/bou1.jpeg
    - images/bou2.jpg
    - images/bou3.jpg
    - images/bou4.jpg
    - images/patan.jpeg
    - images/patan1.jpg
    - images/patan2.jpg
    - images/patan3.jpg
    - images/patan4.jpeg
    - images/shiva2.jpg
    - images/shiva3.jpg
    - images/shiva4.jpg
    - images/nepal1.jpg
    - images/pas.png
    - images/pas1.jpg
    - images/pas2.jpeg
    - images/pas3.jpg
    - images/pas4.jpg
    - assets/interested.db
    - assets/images/a2.jpg
    - assets/images/b2.jpg
    - assets/images/c2.jpg
    - assets/images/d2.jpg
    - assets/images/e2.jpg
    - assets/images/g2.jpg
    - assets/images/h2.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/a1.jpg
    - assets/images/b1.jpg
    - assets/images/c1.jpg
    - assets/images/d1.jpg
    - assets/images/e1.jpg
    - assets/images/f1.jpg
    - assets/images/g1.jpg
    - assets/images/a3.jpg
    - assets/images/b3.jpg
    - assets/images/c3.jpg
    - assets/images/pat.png
    - assets/images/syam.png
    - assets/images/ramn.png
    - assets/images/shiva.png
    - assets/images/grad.png
    - assets/images/culture.png
    - assets/login.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: Laila
      fonts:
        - asset: fonts/Laila-Regular.ttf
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-Regular.ttf
        - asset: fonts/ZillaSlab-Italic.ttf
          style: italic
        - asset: fonts/ZillaSlab-Bold.ttf
          weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages